### ISSUE TITLE
Installation failure: Configuring Incomplete

### ISSUE THREAD

**Issue by cthoyt** [rdkit/homebrew-rdkit#62] opened 2018-04-29 10:54 UTC
After running `brew install rdkit`, I'm getting the following errors. Any help is appreciated.

Note: I'm on OSX 10.13.3, and I've completely uninstalled everything (python@2, python, boost, boost-python, bumpy) before starting. My path variable is set in my `.bashrc` as `export PATH=~/.local/bin:/usr/local/sbin:$PATH`

```bash
$ brew install rdkit
==> Installing rdkit from rdkit/rdkit
==> Installing dependencies for rdkit/rdkit/rdkit: boost, python, boost-python, python@2, numpy
==> Installing rdkit/rdkit/rdkit dependency: boost
==> Downloading https://homebrew.bintray.com/bottles/boost-1.67.0_1.high_sierra.bottle.tar.gz
Already downloaded: /Users/cthoyt/Library/Caches/Homebrew/boost-1.67.0_1.high_sierra.bottle.tar.gz
==> Pouring boost-1.67.0_1.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/boost/1.67.0_1: 13,506 files, 450.9MB
==> Installing rdkit/rdkit/rdkit dependency: python
==> Downloading https://homebrew.bintray.com/bottles/python-3.6.5.high_sierra.bottle.1.tar.gz
Already downloaded: /Users/cthoyt/Library/Caches/Homebrew/python-3.6.5.high_sierra.bottle.1.tar.gz
==> Pouring python-3.6.5.high_sierra.bottle.1.tar.gz
==> /usr/local/Cellar/python/3.6.5/bin/python3 -s setup.py --no-user-cfg install --force --verbose --in
==> /usr/local/Cellar/python/3.6.5/bin/python3 -s setup.py --no-user-cfg install --force --verbose --in
==> /usr/local/Cellar/python/3.6.5/bin/python3 -s setup.py --no-user-cfg install --force --verbose --in
==> Caveats
Python has been installed as
  /usr/local/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /usr/local/opt/python/libexec/bin

If you need Homebrew's Python 2.7 run
  brew install python@2

Pip, setuptools, and wheel have been installed. To update them run
  pip3 install --upgrade pip setuptools wheel

You can install Python packages with
  pip3 install <package>
They will install into the site-package directory
  /usr/local/lib/python3.6/site-packages

See: https://docs.brew.sh/Homebrew-and-Python
==> Summary
🍺  /usr/local/Cellar/python/3.6.5: 4,736 files, 99.2MB
==> Installing rdkit/rdkit/rdkit dependency: boost-python
==> Downloading https://homebrew.bintray.com/bottles/boost-python-1.67.0.high_sierra.bottle.tar.gz
Already downloaded: /Users/cthoyt/Library/Caches/Homebrew/boost-python-1.67.0.high_sierra.bottle.tar.gz
==> Pouring boost-python-1.67.0.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/boost-python/1.67.0: 459 files, 17.3MB
==> Installing rdkit/rdkit/rdkit dependency: python@2
==> Downloading https://homebrew.bintray.com/bottles/python@2-2.7.14_3.high_sierra.bottle.2.tar.gz
Already downloaded: /Users/cthoyt/Library/Caches/Homebrew/python@2-2.7.14_3.high_sierra.bottle.2.tar.gz
==> Pouring python@2-2.7.14_3.high_sierra.bottle.2.tar.gz
==> /usr/local/Cellar/python@2/2.7.14_3/bin/python -s setup.py --no-user-cfg install --force --verbose 
==> /usr/local/Cellar/python@2/2.7.14_3/bin/python -s setup.py --no-user-cfg install --force --verbose 
==> /usr/local/Cellar/python@2/2.7.14_3/bin/python -s setup.py --no-user-cfg install --force --verbose 
==> Caveats
Pip and setuptools have been installed. To update them
  pip install --upgrade pip setuptools

You can install Python packages with
  pip install <package>

They will install into the site-package directory
  /usr/local/lib/python2.7/site-packages

See: https://docs.brew.sh/Homebrew-and-Python
==> Summary
🍺  /usr/local/Cellar/python@2/2.7.14_3: 4,669 files, 82.4MB
==> Installing rdkit/rdkit/rdkit dependency: numpy
==> Downloading https://homebrew.bintray.com/bottles/numpy-1.14.3.high_sierra.bottle.tar.gz
Already downloaded: /Users/cthoyt/Library/Caches/Homebrew/numpy-1.14.3.high_sierra.bottle.tar.gz
==> Pouring numpy-1.14.3.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/numpy/1.14.3: 939 files, 24.9MB
==> Installing rdkit/rdkit/rdkit
==> Downloading https://github.com/rdkit/rdkit/archive/Release_2017_09_3.tar.gz
Already downloaded: /Users/cthoyt/Library/Caches/Homebrew/rdkit-2017.09.3.tar.gz
==> cmake -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/u
Last 15 lines from /Users/cthoyt/Library/Logs/Homebrew/rdkit/01.cmake:
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   thread
--   system
--   chrono
--   date_time
--   atomic
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   serialization
== Using strict rotor definition
== Updating Filters.cpp from pains file
== Done updating pains files
-- Configuring incomplete, errors occurred!
See also "/tmp/rdkit-20180429-30726-jbbbb9/rdkit-Release_2017_09_3/CMakeFiles/CMakeOutput.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/rdkit/homebrew-rdkit/issues

These open issues may also help:
MacOS: ModuleNotFoundError: No module named 'rdkit' https://github.com/rdkit/homebrew-rdkit/issues/50
Installing RDKit on Mac OSX 10.10.2 with java and inchi https://github.com/rdkit/homebrew-rdkit/issues/25
```

I'm also having the issue that the log file it references, `/tmp/rdkit-20180429-30726-jbbbb9/rdkit-Release_2017_09_3/CMakeFiles/CMakeOutput.log` doesn't exist.

**Comment by kim-branson** [comment] 2018-05-02 21:38
i have the same issue. 
if you look at the log in 
`/Users/bransonk/Library/Logs/Homebrew/rdkit/01.cmake`

for you it is `/Users/cthoyt/Library/Logs/Homebrew/rdkit/01.cmake`

i have the following:

```

CMake Error at /usr/local/Cellar/cmake/3.11.1/share/cmake/Modules/FindBoost.cmake:2044 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.67.0

  Boost include path: /usr/local/include

  Could not find the following Boost libraries:

          boost_python

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  CMakeLists.txt:171 (find_package)


Python Install directory /usr/local/Cellar/rdkit/2017.09.3/lib/python3.6/site-packages
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   regex
== OSX: CHECKING for libc++
== BOOST USES LIBC++
-- Found Eigen3: /usr/local/include/eigen3 (Required is at least version "2.91.0") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   thread
```

i've set the following env vars:
```
export BOOST_LIBRARYDIR="/usr/local/Cellar"
export BOOST_ROOT="/usr/local/Cellar/boost"```

which may not be correct, but haven't solved the issue either.

**Comment by tbrx** [comment] 2018-05-07 19:34
Having the same issue as well, on OSX 10.11.6. I had hoped re-installing and re-linking any of `boost`, `boost-python`, or `boost-python3` would fix things, but no. I'm using homebrew python for both 2.7 and 3.6.

I confirmed that I do indeed have boost at `/usr/local/include/boost`, but tried including the paths `BOOST_LIBRARYDIR` and `BOOST_ROOT` as cmake flags (pointing at `/usr/local/Cellar`), also to no effect.

**Comment by greglandrum** [comment] 2018-05-08 12:56
This is unfortunately unlikely to work with boost=1.67. There are likely to be problems with cmake and I have yet to do any testing whatsoever of the RDKit with that version of boost.
I'd really recommend stepping back to boost 1.65 and using that.

**Comment by dbdbaron** [comment] 2018-05-14 17:46
I'm trying with boost 1.60 (brew search boost didn't show a 1.65) and still getting the `Configuring incomplete` error.

**Comment by kzhk75** [comment] 2018-05-25 12:12
With the information of this thready, I tried the following link, http://goingmyway.cn/2018/02/06/Homebrew-how-to-install-boost-with-a-specific-version/ , to install boost 1.65 on my MacOS through brew: `brew install --build-from-source boost boost-python boost-python3`
I slightly modified the link to downgrade from 1.67 to 1.65.1. It works well for my Mac(High Sierra, Yosemite)


Here is a simple patch as an example:
```
$ diff -aur orig/boost.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/
--- orig/boost.rb	2018-05-25 10:44:31.000000000 +0900
+++ /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/boost.rb	2018-05-25 10:47:54.000000000 +0900
@@ -5,8 +5,8 @@
   head "https://github.com/boostorg/boost.git"
 
   stable do
-    url "https://dl.bintray.com/boostorg/release/1.67.0/source/boost_1_67_0.tar.bz2"
-    sha256 "2684c972994ee57fc5632e03bf044746f6eb45d4920c343937a465fd67a5adba"
+    url "https://dl.bintray.com/boostorg/release/1.65.1/source/boost_1_65_1.tar.bz2"
+    sha256 "9807a5d16566c57fd74fb522764e0b134a8bbe6b6e8967b83afefd30dcd3be81"
 
     # Remove for > 1.67.0
     # Fix "error: no member named 'next' in namespace 'boost'"
```

**Comment by hsiaoyi0504** [comment] 2018-06-04 15:30
You can also try install HEAD version. Recent build shows that it will work https://travis-ci.org/rdkit/homebrew-rdkit/jobs/387705627.

**Comment by kim-branson** [comment] 2018-06-06 20:56
`brew install --HEAD rdkit`  worked for me with  homebrew python3 installed with
`brew install boost-python3 python3`

**Comment by UnixJunkie** [comment] 2019-09-18 07:23
This is too old, so I am closing.
Also, there is a PR fixing boost and boost-python3 to 1.70, because rdkit  2019.03.2
is known to compile with them.

**Closed by UnixJunkie** 2019-09-18 07:23 UTC
